from tests.async_mock import AsyncMock

_AUTH_RESPONSE = '''{
    "platformType": "uplay",
    "ticket": "LongTicket",
    "twoFactorAuthenticationTicket": None,
    "profileId": "12345",
    "userId": "Mock",
    "nameOnPlatform": "KptMock",
    "environment": "Prod",
    "expiration": "2019-03-05T11:28:49.0783145Z",
    "spaceId": "1234",
    "clientIp": "420.BL.4ZE.IT",
    "clientIpCountry": "US",
    "serverTime": "2019-03-05T08:28:49.0792996Z",
    "sessionId": "Session_id",
    "sessionKey": "Session_key",
    "rememberMeTicket": "Rememeber_me"
}'''


class BackendClientMock(AsyncMock):
    def authorize(self, auth_code):
        pass

    def set_auth_lost_callback(self, callback):
        pass

    def is_authenticated(self):
        return True

    async def authorise_with_stored_credentials(self, credentials):
        return await self.get_user_data()

    async def authorise_with_cookies(self, credentials):
        return {'userId': '123', 'username': 'Mock'}

    def restore_credentials(self, data):
        pass

    async def get_user_data(self):
        return {'userId': '123', 'username': 'Mock', 'nameOnPlatform': 'MockPl', 'accountIssues': None,
                'communicationOptIn': True, 'communicationThirdPartyOptIn': False, 'country': 'US',
                'dateCreated': '2017-11-06T17:57:05.9770000Z', 'dateOfBirth': '1990-01-01T00:00:00.0000000Z',
                'email': 'mocker@gmail.com', 'firstName': None, 'gender': None, 'hasAcceptedLegalOptins': True,
                'lastName': None, 'preferredLanguage': 'en',
                'status': {'autoGeneratedUsername': False, 'dateOfBirthApproximated': False, 'invalidEmail': False,
                           'missingRequiredInformation': False, 'pendingDeactivation': False,
                           'recoveringPassword': False, 'passwordUpdateRequired': False, 'reserved': False,
                           'changeEmailPending': False, 'inactiveAccount': False, 'generalStatus': 'activated',
                           'suspiciousActivity': False, 'locked': False}, 'accountType': 'Ubisoft'}

    async def get_game_stats(self, space_id):
        return {'Statscards': []}

    async def get_friends(self):
        return {'friends': [{'pid': '420', 'nameOnPlatform': 'mocker1', 'lastModified': '2018-12-27T00:00:00.0000000',
                             'state': 'Friends'},
                            {'pid': '123', 'nameOnPlatform': 'mocker2', 'lastModified': '2019-03-29T00:00:00.0000000',
                             'state': 'Friends'},
                            {'pid': '321', 'nameOnPlatform': 'mocker3', 'lastModified': '2019-05-14T00:00:00.0000000',
                             'state': 'Friends'}]}

    async def get_subscription_titles(self):
        return None

    async def get_club_titles(self):
        return {
            "data": {
                "viewer": {
                  "id": "57a84edf-09d7-448f-a18f-09c504b84637",
                  "ownedGames": {
                    "totalCount": 8,
                    "nodes": [
                      {
                        "id": "6678eff0-1293-4f87-8c8c-06a4ca646068",
                        "spaceId": "6678eff0-1293-4f87-8c8c-06a4ca646068",
                        "name": "Assassin's Creed\u00ae Unity",
                        "viewer": {
                          "meta": {
                            "id": "57a84edf-09d7-448f-a18f-09c504b84637-8c8d9b22-498c-45e6-80da-7cd22787c9b3",
                            "ownedPlatformGroups": [
                              [
                                {
                                  "id": "35c5c607-2717-47d9-9323-7df47c6e1c4d",
                                  "name": "PC",
                                  "type": "PC"
                                }
                              ]
                            ]
                          }
                        }
                      },
                      {
                        "id": "f40e304d-8e8d-4343-8270-d06487c35add",
                        "spaceId": "f40e304d-8e8d-4343-8270-d06487c35add",
                        "name": "Far Cry\u00ae 5",
                        "viewer": {
                          "meta": {
                            "id": "57a84edf-09d7-448f-a18f-09c504b84637-8c8d9b22-498c-45e6-80da-7cd22787c9b3",
                            "ownedPlatformGroups": [
                              [
                                {
                                  "id": "35c5c607-2717-47d9-9323-7df47c6e1c4d",
                                  "name": "PC",
                                  "type": "PC"
                                }
                              ],
                              [
                                {
                                  "id": "35c5c607-2717-47d9-9323-7df47c6e1c4d",
                                  "name": "stadia",
                                  "type": "STADIA"
                                }
                              ]
                            ]
                          }
                        }
                      },
                      {
                        "id": "6edd234a-abff-4e90-9aab-b9b9c6e49ff7",
                        "spaceId": "6edd234a-abff-4e90-9aab-b9b9c6e49ff7",
                        "name": "Tom Clancy's The Division\u2122 ",
                        "viewer": {
                          "meta": {
                            "id": "57a84edf-09d7-448f-a18f-09c504b84637-8c8d9b22-498c-45e6-80da-7cd22787c9b3",
                            "ownedPlatformGroups": [
                              [
                                {
                                  "id": "35c5c607-2717-47d9-9323-7df47c6e1c4d",
                                  "name": "PC",
                                  "type": "PC"
                                }
                              ]
                            ]
                          }
                        }
                      },
                      {
                        "id": "1d1273d9-2120-4e55-8d98-66e08781258e",
                        "spaceId": "1d1273d9-2120-4e55-8d98-66e08781258e",
                        "name": "Trackmania Turbo",
                        "viewer": {
                          "meta": {
                            "id": "57a84edf-09d7-448f-a18f-09c504b84637-8c8d9b22-498c-45e6-80da-7cd22787c9b3",
                            "ownedPlatformGroups": [
                              [
                                {
                                  "id": "35c5c607-2717-47d9-9323-7df47c6e1c4d",
                                  "name": "PC",
                                  "type": "PC"
                                }
                              ]
                            ]
                          }
                        }
                      },
                      {
                        "id": "50228b8c-bbaa-4c32-83c6-2831a1ac317c",
                        "spaceId": "50228b8c-bbaa-4c32-83c6-2831a1ac317c",
                        "name": "Far Cry\u00ae 3",
                        "viewer": {
                          "meta": {
                            "id": "57a84edf-09d7-448f-a18f-09c504b84637-8c8d9b22-498c-45e6-80da-7cd22787c9b3",
                            "ownedPlatformGroups": [
                              [
                                {
                                  "id": "35c5c607-2717-47d9-9323-7df47c6e1c4d",
                                  "name": "PC",
                                  "type": "PC"
                                }
                              ]
                            ]
                          }
                        }
                      },
                      {
                        "id": "4bd0476b-acec-446d-b526-23a0209101ca",
                        "spaceId": "4bd0476b-acec-446d-b526-23a0209101ca",
                        "name": "Far Cry\u00ae 3 Blood Dragon",
                        "viewer": {
                          "meta": {
                            "id": "57a84edf-09d7-448f-a18f-09c504b84637-8c8d9b22-498c-45e6-80da-7cd22787c9b3",
                            "ownedPlatformGroups": [
                              [
                                {
                                  "id": "35c5c607-2717-47d9-9323-7df47c6e1c4d",
                                  "name": "PC",
                                  "type": "PC"
                                }
                              ]
                            ]
                          }
                        }
                      },
                      {
                        "id": "4bd0476b-acec-446d-b526-23a0209101ca",
                        "spaceId": "4bd0476b-acec-446d-b526-23a0209101ca",
                        "name": "ONLY_STADIA_GAME",
                        "viewer": {
                          "meta": {
                            "id": "57a84edf-09d7-448f-a18f-09c504b84637-8c8d9b22-498c-45e6-80da-7cd22787c9b3",
                            "ownedPlatformGroups": [
                              [
                                {
                                  "id": "35c5c607-2717-47d9-9323-7df47c6e1c4d",
                                  "name": "stadia",
                                  "type": "STADIA"
                                }
                              ]
                            ]
                          }
                        }
                      },
                    ]
                  }
                }
            }
        }

    def get_applications(self):
        pass

    async def get_subscription(self):
        pass
