name: Python package
on:
  workflow_run:
    workflows: ["Update release version"]
    types:
      - completed
  push:
    branches: [ master ]
    
  pull_request:
    branches: [ master, dev ]
    types:
      - synchronize

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.7' 
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x86' 
    # You can test your matrix by printing the current Python version
    
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        py  -3.7-32 -m pip install --upgrade pip
        py  -3.7-32 -m pip install -r requirements/app.txt
        py  -3.7-32 -m pip install -r requirements/app.txt --target ./src/
    
    
    - name: Create zip archive
      shell: bash
      env:
        ZIP_NAME: uplay_win_afb5a69c-b2ee-4d58-b916-f4cd75d4999a
      run: |
        7z a ${ZIP_NAME}.zip ./src/*
        
    - name: get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with: 
        path: 'src/manifest.json'
        prop_path: 'version'
    
    - name: Upload result
      uses: actions/upload-artifact@v1
      with:
        name: uplay_win_${{steps.version.outputs.prop}}
        path: uplay_win_afb5a69c-b2ee-4d58-b916-f4cd75d4999a.zip
        
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@latest
      with:
        # GitHub secret token
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        # Git tag (for automatic releases)
        automatic_release_tag: early_release_${{steps.version.outputs.prop}}
        # Should this release be marked as a pre-release?
        prerelease: True
        # Release title (for automatic releases)
        title: early_release_${{steps.version.outputs.prop}}
        # Assets to upload to the release
        files: uplay_win_afb5a69c-b2ee-4d58-b916-f4cd75d4999a.zip
